# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-12-04 12:52:33
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *

def Model4():  # Model4

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")

    TSC_crime_main_y_shp = "C:\\P7_pyt\\time_series_cluster\\TSC_crime_main_y.shp"
    clusters_hovedstad_clean_shp = "C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp"

    # Process: Feature to Raster (Feature to Raster) (conversion)
    Feature_TSC_1 = "C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\Feature_TSC_1"
    with arcpy.EnvManager(extent=clusters_hovedstad_clean_shp):
        arcpy.conversion.FeatureToRaster(in_features=TSC_crime_main_y_shp, field="CLUSTER_ID", out_raster=Feature_TSC_1, cell_size="100")
        Feature_TSC_1 = arcpy.Raster(Feature_TSC_1)

    # Process: Reclassify (Reclassify) (sa)
    crime_reclass = "C:\\P7_pyt\\tsc_reclass\\crime_reclass"
    Reclassify = crime_reclass
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS[\"ETRS_1989_UTM_Zone_32N\",GEOGCS[\"GCS_ETRS_1989\",DATUM[\"D_ETRS_1989\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",9.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]"):
        crime_reclass = arcpy.sa.Reclassify(Feature_TSC_1, "VALUE", "1 3;2 3;3 3;4 2;5 1;6 6", "NODATA")
        crime_reclass.save(Reclassify)


    # Process: Weighted Overlay (Weighted Overlay) (sa)
    Weighte_crim1 = "C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\Weighte_crim1"
    Weighted_Overlay = Weighte_crim1
    Weighte_crim1 = arcpy.sa.WeightedOverlay(WOTable([[crime_reclass, 100 , 'VALUE' , RemapValue([[1, 1], [2, 2], [3, 3], [6, 9], ['NODATA', 'NODATA']])]], [1, 9, 1]))
    Weighte_crim1.save(Weighted_Overlay)


    # Process: Raster to Point (Raster to Point) (conversion)
    tsc_point = "C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\tsc_point"
    arcpy.conversion.RasterToPoint(in_raster=Weighte_crim1, out_point_features=tsc_point)

    # Process: Spatial Join (Spatial Join) (analysis)
    tsc_point_SpatialJoin = "C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\tsc_point_SpatialJoin"
    arcpy.analysis.SpatialJoin(target_features=tsc_point, join_features=clusters_hovedstad_clean_shp, out_feature_class=tsc_point_SpatialJoin, field_mapping="POINTID \"POINTID\" true true false 0 Long 0 0,First,#,C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\tsc_point,POINTID,-1,-1;GRID_CODE \"GRID_CODE\" true true false 0 Long 0 0,First,#,C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb\\tsc_point,GRID_CODE,-1,-1;fid_1 \"fid_1\" true true false 19 Double 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,fid_1,-1,-1;munic_code \"munic_code\" true true false 19 Double 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,munic_code,-1,-1;id_munic \"id_munic\" true true false 19 Double 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,id_munic,-1,-1;munic_clus \"munic_clus\" true true false 254 Text 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,munic_clus,0,253;Shape_Leng \"Shape_Leng\" true true false 19 Double 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,Shape_Leng,-1,-1;Shape_Area \"Shape_Area\" true true false 19 Double 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,Shape_Area,-1,-1;cluster_id \"cluster_id\" true true false 254 Text 0 0,First,#,C:\\P7_pyt\\GIS_lag\\clusters_hovedstad_clean.shp,cluster_id,0,253", match_option="COMPLETELY_WITHIN")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb", workspace="C:\\Users\\nalda\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\P7 - Gentrification\\SPLM1_project\\SPLM1_project.gdb"):
        Model4()
